id: P003157
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 10:44:07.726597
source_metadata:
  id: bdr:W1PD90026
  title: ཝུན་ཁྲོན་རྫོང་གི་ལོ་རྒྱུས།
  author: ''
  volumes:
    2220056c34e640c6ba32174dc24fec49:
      image_group_id: I1PD90098
      title: ''
      volume_number: 1
      total_pages: 964
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
